version: '3'
services:
  service-app:
    container_name: articles_management_service
    build: './'
    image: shalinipuri/articles_management_service:gke-mysql
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: on-failure