apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-mgmt-api-deploy
  labels:
    name: articles-mgmt-api-deploy
    app: articles-management
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      name: articles-mgmt-api-pod
      app: articles-management
  template:
    metadata:
      name: articles-mgmt-api-pod
      labels:
        name: articles-mgmt-api-pod
        app: articles-management
    spec:
      containers:
        - name: articles-management-api-image
          image: shalinipuri/articlesmanagement:firstimage
          imagePullPolicy: Always
          env:
          - name: MYSQL_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: root-password
          envFrom:
            - configMapRef:
                name: database-config
          ports:
            - containerPort: 5000
