apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name:  articles-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  articles-management
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 30Mi