apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-preload-data-config
  labels:
    name: mysql-data-store
    app: mysql-gke-deployment
  namespace: development
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS`articles-management-db`;
    USE `articles-management-db`;
    DROP TABLE IF EXISTS `articles`;
    CREATE TABLE `articles`(
     `id`int NOT NULL AUTO_INCREMENT,
     `title`varchar(255) NOT NULL,
     `author`varchar(255) NOT NULL,
     `language`varchar(255) DEFAULT NULL,
     `created_at`datetime DEFAULT CURRENT_TIMESTAMP,
     `created_by`varchar(255) DEFAULT NULL,
     `updated_at`datetime DEFAULT CURRENT_TIMESTAMP,
     `updated_by` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    );
    insert into articles(`title`,`author`,`language`) values('We Fools ourseleves','Abhishek Chakraborty','English');`