apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
    app: mysql-gke-deployment
  namespace: development
spec:
  type: ClusterIP
  selector:
    name: mysql-pod
    app: mysql-gke-deployment
  ports:
    - port: 3306
      targetPort: 3306